import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "nextjs 基礎",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <header className="bg-slate-700 p-4 text-xl font-semibold text-white flex justify-between">
          <Link href="/">Blog</Link>
          <Link href="/contact">お問い合わせ</Link>
        </header>
        {children}
      </body>
    </html>
  );
}
